"""init migrate

Revision ID: b6ab94239019
Revises: 
Create Date: 2020-02-19 10:49:10.670694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6ab94239019'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sign_record', 'late_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='迟到时长（分钟），默认0',
               existing_comment='???????????0',
               existing_nullable=True)
    op.alter_column('user', 'face',
               existing_type=mysql.VARCHAR(length=200),
               comment='人脸位置信息',
               existing_comment='??????',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='工号',
               existing_comment='??',
               autoincrement=True)
    op.alter_column('user', 'openid',
               existing_type=mysql.VARCHAR(length=100),
               comment='小程序openid',
               existing_comment='???openid')
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('root', 'admin', 'leader', 'staff'),
               comment='用户角色',
               existing_comment='????',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('root', 'admin', 'leader', 'staff'),
               comment='????',
               existing_comment='用户角色',
               existing_nullable=False)
    op.alter_column('user', 'openid',
               existing_type=mysql.VARCHAR(length=100),
               comment='???openid',
               existing_comment='小程序openid')
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='??',
               existing_comment='工号',
               autoincrement=True)
    op.alter_column('user', 'face',
               existing_type=mysql.VARCHAR(length=200),
               comment='??????',
               existing_comment='人脸位置信息',
               existing_nullable=False)
    op.alter_column('sign_record', 'late_time',
               existing_type=mysql.INTEGER(display_width=11),
               comment='???????????0',
               existing_comment='迟到时长（分钟），默认0',
               existing_nullable=True)
    # ### end Alembic commands ###
